deployment:
  image:
    name: vanlahuynhduc/exchange-ws
    tags:
      stable: 0.0.2-16c5683b
      canary: 0.0.4-a0ee77c6
    repository:
imageCredentials:
  registry: https://index.docker.io/v1/
  username: vanlahuynhduc/exchange-ws
  password:
replicas:
  min: 1
  max: 2
