deployment:
  image:
    name: vanlahuynhduc/exchange-ws
    tags:
      stable: 0.0.2-2a4f9a2e
      canary: 0.0.2-ab46019f
    repository:
imageCredentials:
  registry: https://index.docker.io/v1/
  username: vanlahuynhduc/exchange-ws
  password:
replicas:
  min: 1
  max: 2
