# ...existing code...
spec:
  template:
    spec:
      containers:
        - name: exchange-ws
          # ...existing code...
          volumeMounts:
            - name: config-volume
              mountPath: /app/config.json
              subPath: config.json
      volumes:
        - name: config-volume
          configMap:
            name: exchange-config
# ...existing code...
