apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: argocd-demo-gateway
  namespace: dev
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "hihi.itmosvn.me"