apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Release.Name }}-gateway
  namespace: dev
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 3001
      name: http-3001
      protocol: HTTP
    hosts:
    - "hihi.itmosvn.me"