apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: argocd-demo-virtualservice
spec:
  hosts:
  - "hihi.itmosvn.me"
  gateways:
  - argocd-demo-gateway
  http:
  - route:
    - destination:
        host: argocd-demo
        subset: stable
      weight: 80
    - destination:
        host: argocd-demo
        subset: canary
      weight: 20

---

apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: argocd-demo-destinationrule
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  host: argocd-demo
  subsets:
  - name: stable
    labels:
      version: stable
  - name: canary
    labels:
      version: canary