apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-virtualservice
spec:
  hosts:
  - "hihi.itmosvn.me"
  gateways:
  - {{ .Release.Name }}-gateway
  http:
  - route:
    - destination:
        host: {{ .Release.Name }}
        subset: stable
      weight: 80
    - destination:
        host: {{ .Release.Name }}
        subset: canary
      weight: 20

---

apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ .Release.Name }}-destinationrule
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  host: {{ .Release.Name }}
  subsets:
  - name: stable
    labels:
      version: stable
  - name: canary
    labels:
      version: canary