apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: exchange-be-virtualservice
spec:
  hosts:
  - "*"
  gateways:
  - example-gateway
  http:
  - route:
    - destination:
        host: example-service
        subset: stable
      weight: 80
    - destination:
        host: example-service
        subset: canary
      weight: 20

---

apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: example-destinationrule
spec:
  host: example-service
  subsets:
  - name: stable
    labels:
      version: stable
  - name: canary
    labels:
      version: canary