apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: exchange-ws-rollout
spec:
  replicas: 10
  selector:
    matchLabels:
      app: argocd-demo
  template:
    metadata:
      labels:
        app: argocd-demo
    spec:
      containers:
      - name: argocd-demo
        image: vanlahuynhduc/example-app:8.8.3-SNAPSHOT-b067bbfb2a253b147a714ef20544f3182d84e659
        ports:
        - containerPort: 80
  strategy:
    canary:
      maxSurge: 25%
      maxUnavailable: 0
      steps:
      - setWeight: 10
      - pause: {duration: 1h}
      - setWeight: 20
      - pause: {}