apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-registry-secret
  labels:
    release: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": pre-install
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
