apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    - name: http-3000
      port: 3000
      targetPort: 3000
    - name: ws-3003
      port: 3003
      targetPort: 3003