apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
    - name: http-ws
      port: 3003
      targetPort: 3003
      protocol: TCP