apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-main
spec:
  selector:
    app: {{ .Release.Name }}-main
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ws
spec:
  selector:
    app: {{ .Release.Name }}-ws
  ports:
    - name: http-ws
      port: 3003
      targetPort: 3003
      protocol: TCP