apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: exchange
  namespace: argocd
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
        - values.yaml
    path: charts/exchange-ws
    repoURL: https://github.com/huynhduc0/exchange-ws
    targetRevision: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
