name: Build and Push Docker Image

on:
  push:
    branches:
      - main
env:
  DOCKER_SERVER: docker.io
  DOCKER_REGISTRY: vanlahuynhduc
  DOCKER_IMAGE_NAME: exchange-ws

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract version from package.json
        id: extract_version
        run: |
          VERSION=$(jq -r '.version' package.json)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Get short SHA
        id: vars
        run: echo "GITHUB_SHA_SHORT=${GITHUB_SHA::8}" >> $GITHUB_ENV

      - name: Build the Docker image
        env:
          DOCKER_SERVER: ${{ env.DOCKER_SERVER }}
          DOCKER_REGISTRY: ${{ env.DOCKER_REGISTRY }}
          DOCKER_IMAGE_NAME: ${{ env.DOCKER_IMAGE_NAME }}
          VERSION: ${{ env.VERSION }}
          GITHUB_SHA_SHORT: ${{ env.GITHUB_SHA_SHORT }}
        run: |
          docker build . -t $DOCKER_SERVER/$DOCKER_REGISTRY/$DOCKER_IMAGE_NAME:$VERSION-$GITHUB_SHA_SHORT

      - name: Push the Docker image
        env:
          DOCKER_SERVER: ${{ env.DOCKER_SERVER }}
          DOCKER_REGISTRY: ${{ env.DOCKER_REGISTRY }}
          DOCKER_IMAGE_NAME: ${{ env.DOCKER_IMAGE_NAME }}
          VERSION: ${{ env.VERSION }}
          GITHUB_SHA_SHORT: ${{ env.GITHUB_SHA_SHORT }}
        run: |
          docker push $DOCKER_SERVER/$DOCKER_REGISTRY/$DOCKER_IMAGE_NAME:$VERSION-$GITHUB_SHA_SHORT

      - name: Update chart values
        run: |
          sed -i "s|name:.*|name: $DOCKER_REGISTRY/$DOCKER_IMAGE_NAME|" charts/exchange-ws/values.yaml
          sed -i "s|tag:.*|tag: $VERSION-$GITHUB_SHA_SHORT|" charts/exchange-ws/values.yaml

      - name: Commit and push changes to main branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add charts/exchange-ws/values.yaml
          git commit -m "Update chart values with new image tag"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git main

      - name: Create a tag to trigger ArgoCD
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git tag $DOCKER_IMAGE_NAME:$VERSION-$GITHUB_SHA_SHORT
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git $DOCKER_IMAGE_NAME:$VERSION-$GITHUB_SHA_SHORT

      - name: Merge main to dev branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git checkout dev
          git merge main
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git dev